version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - andreogle
  ignore:
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
  - dependency-name: ethereum-waffle
    versions:
    - 3.3.0
  - dependency-name: hardhat
    versions:
    - 2.0.11
  - dependency-name: ethers
    versions:
    - 5.0.27
